# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount
lsi:      false
paginate: 50

# configuration required for some pages

domain: blog.eamonn.org
title: Eamonn O'Brien-Strain
author: Eamonn O'Brien-Strain
email: eob@well.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

github:
   username: eobrain

# disqus:
#   id: disqusid
