# standard jekyll configuration

permalink: date
highlighter: rouge
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount
lsi:      false
paginate: 60
gems: [jekyll-paginate]

# configuration required for some pages

domain: blog.eamonn.org
title: Eamonn O'Brien-Strain
author: Eamonn O'Brien-Strain
email: eob@well.com
#chiefimage: http://localhost:8080/?page=
chiefimage: http://chiefimage.appspot.com/?page=

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

github:
   username: eobrain

# disqus:
#   id: disqusid
